### DISCUSSION TITLE
How to make sure that a newly rebuilt image is used from my repository

### DISCUSSION THREAD

**Discussion by adayaru** [vhive-serverless/vHive#587] [Q&A]
I am trying out the sample helloworld example for vhive (firecracker-containerd) with a yaml like below:

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: crccheck/hello-world:latest # Stub image. See https://github.com/ease-lab/vhive/issues/68
          ports:
            - name: h2c # For GRPC support
              containerPort: 50051
          env:
            - name: GUEST_PORT # Port on which the firecracker-containerd container is accepting requests
              value: "50051"
            - name: GUEST_IMAGE # Container image to use for firecracker-containerd container
              value: "ghcr.io/ease-lab/helloworld:var_workload"
```
I am using my own public docker repository image. When I rebuild the image and push it - I see that it is not getting picked up by the next run. It seems to use a cached version always. I tried adding "imagePullPolicy: Always" - but see that it is futile since it applies to the image:
`image: crccheck/hello-world:latest`

How can I make the service pick up my newly built image?
